/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i obextransfer.h -p obex_objectpush_p.h:obex_objectpush.cpp org.bluez.obex.client.all.xml org.bluez.obex.ObjectPush
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OBEX_OBJECTPUSH_P_H_1438942816
#define OBEX_OBJECTPUSH_P_H_1438942816

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "obextransfer.h"

/*
 * Proxy class for interface org.bluez.obex.ObjectPush
 */
class OrgBluezObexObjectPushInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.bluez.obex.ObjectPush"; }

public:
    OrgBluezObexObjectPushInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgBluezObexObjectPushInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<ObexTransfer> ExchangeBusinessCards(const QString &in0, const QString &in1)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0) << QVariant::fromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("ExchangeBusinessCards"), argumentList);
    }

    inline QDBusPendingReply<ObexTransfer> PullBusinessCard(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("PullBusinessCard"), argumentList);
    }

    inline QDBusPendingReply<ObexTransfer> SendFile(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("SendFile"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace bluez {
    namespace obex {
      typedef ::OrgBluezObexObjectPushInterface ObjectPush;
    }
  }
}
#endif
