/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i obextransfer.h -p obex_objectpush_p.h:obex_objectpush.cpp org.bluez.obex.client.all.xml org.bluez.obex.ObjectPush
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "obex_objectpush_p.h"

/*
 * Implementation of interface class OrgBluezObexObjectPushInterface
 */

OrgBluezObexObjectPushInterface::OrgBluezObexObjectPushInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgBluezObexObjectPushInterface::~OrgBluezObexObjectPushInterface()
{
}

